config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  root "links#index"
  get '/about',         to: "static_pages#about", as:   "about"   #about_path/url
  get "/ask",           to: "questions#index",    as:   "ask"     #ask_path/url
  get "/new",           to: "links#index",        as:   "new"     #new_path/url
  get "/comments",      to: "comments#index",     as:   "comments"#comments_path/url
  delete "/signout",    to: "sessions#destroy",   as:   "signout" #signout_path/url
  get "/signin",        to: "sessions#new",       as:   "signin"  #signin_path/url
  post "/signin",       to: "sessions#create"
  get "/signup",        to: "users#new",          as:   "signup"  #signup_path/url

  resources :users
  resources :links do
    resources :comments, module: :links
  end
  resources :questions do
    resources :comments, module: :questions
  end
  resources :upvotes
  resources :conversations do
    resources :messages

    collection do
      get :inbox
      get :all, action: :index
      get :sent
      get :trash
    end
  end
  # redirect back to root_path if bad GET request is made
  get '*a' => redirect { |p, req| req.flash[:danger] = "Ah snap! Hitmunk couldn't find that page."; '/' }
end

app/models/comment.rb
class Comment < ApplicationRecord
  # Active Record Associations
  belongs_to :commentable, polymorphic: true, counter_cache: true # counter_cache belongs on child model because that's the trigger action on object.comments_count
  belongs_to :user

  # Active Record Validations
  validates :body, presence: true

  # refactor this into a scope
  def self.sort_by_created_at
    self.order('created_at desc')
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_signin, only: [:create]

  def index
    @comments = Comment.sort_by_created_at
  end

  def create
    @comment = @commentable.comments.new(comments_params)
    @comment.user = current_user
    if @comment.save
      calculate_points_for(@comment.user, 1)
      flash[:success] = "Your comment has been added, #{@comment.user.username}!"
      redirect_to @commentable
    else
      redirect_to @commentable
    end
  end

  def report
    # generate_report()
    CommentWorker.perform_async("01-01-2017", "12-31-2017")
    render text: "REQUEST TO GENERATE A COMMENT ADDED TO QUEUE"
  end

  private

  def comments_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/links/comments_controller.rb
class Links::CommentsController < CommentsController
  before_action :set_commentable

  def index
    redirect_to root_path
  end

  private

  def set_commentable
    @commentable = Link.find_by_slug(params[:link_id])
  end
end

app/controllers/questions/comments_controller.rb
class Questions::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
    @commentable = Question.find_by_slug(params[:question_id])
  end
end

app/views/comments/_comments.html.erb
<% commentable.comments.each do |comment| %>
  <div class="well">
    <p><strong><%= link_to comment.user.username, user_path(comment.user) %> says:</strong> <%= comment.body %></p>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [commentable, Comment.new] do |f| %>
  <div class="form-group">
    <%= f.text_area :body, class: "form-control", placeholder: "Add a comment", required: true %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/comments/index.html.erb
<h1>Recent comments</h1>
<% @comments.each do |comment| %>
  <li>"<%= comment.body %>" by <%= link_to comment.user.username, user_path(comment.user) %>
    <% if comment.commentable_type == "Link" %>
      on: <strong><%= link_to comment.commentable.title, link_path(comment.commentable)%></strong>
    <% else %>
      on: <strong><%= link_to comment.commentable.title, question_path(comment.commentable)%></strong>
    <% end %>
    <%= time_ago_in_words(comment.created_at) %> ago</li>
<% end %>