config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  root "links#index"
  get '/about',         to: "static_pages#about", as:   "about"   #about_path/url
  get "/ask",           to: "questions#index",    as:   "ask"     #ask_path/url
  get "/new",           to: "links#index",        as:   "new"     #new_path/url
  get "/comments",      to: "comments#index",     as:   "comments"#comments_path/url
  delete "/signout",    to: "sessions#destroy",   as:   "signout" #signout_path/url
  get "/signin",        to: "sessions#new",       as:   "signin"  #signin_path/url
  post "/signin",       to: "sessions#create"
  get "/signup",        to: "users#new",          as:   "signup"  #signup_path/url

  resources :users
  resources :links do
    resources :comments, module: :links
  end
  resources :questions do
    resources :comments, module: :questions
  end
  resources :upvotes
  resources :conversations do
    resources :messages

    collection do
      get :inbox
      get :all, action: :index
      get :sent
      get :trash
    end
  end
  # redirect back to root_path if bad GET request is made
  get '*a' => redirect { |p, req| req.flash[:danger] = "Ah snap! Hitmunk couldn't find that page."; '/' }
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  def index
    @conversations = current_user.mailbox.conversations
  end

  def inbox
    @conversations = current_user.mailbox.inbox
    render action: :index
  end

  def sent
    @conversations = current_user.mailbox.sentbox
    render action: :index
  end

  def trash
    @conversations = current_user.mailbox.trash
    render action: :index
  end

  def new
    @recipients = User.all - [current_user]
  end

  def create
    receipt = User.find(params[:user_id])
    receipt = current_user.send_message(receipt, params[:body], params[:subject])
    calculate_points_for(current_user, 1)
    redirect_to conversation_path(receipt.conversation)
  end

  def show
    @conversation = current_user.mailbox.conversations.find(params[:id])
    @conversation.mark_as_read(current_user)
  end
end

app/views/conversations/index.html.erb
<% provide(:title, "#{@current_user.username}'s Mailbox") %>
<h1><%= current_user.username %>'s Mailbox</h1>
<div class="row">
  <div class="col-md-4 col-md">
      <%= link_to "New", new_conversation_path %> |
      Unread (<%= current_user.mailbox.inbox.unread(current_user).count %>) |
      Sent Messages (<%= current_user.mailbox.sentbox.count %>) |
      Trashcan (<%= current_user.mailbox.trash.count %>)
    <hr />
  </div>

  <div class="col-md-8 col-md">
    <% @conversations.each do |conversation| %>
      <div>
        <% if conversation.is_unread?(current_user) %>
          <strong><%= link_to conversation.subject, conversation_path(conversation) %></strong>
        <% else %>
          <%= link_to conversation.subject, conversation_path(conversation) %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/conversations/new.html.erb
<% provide(:title, "Start a new conversation") %>
<h1>Start a new conversation</h1>

<%= form_tag conversations_path, method: :post do %>
  <div>
    <%= select_tag :user_id, options_from_collection_for_select(@recipients, :id, :username) %>
  </div>

  <div>
    <%= text_field_tag :subject, nil, placeholder: "Subject" %>
  </div>

  <div>
    <%= text_area_tag :body, nil, placeholder: "Write your message here..." %>
  </div>

  <%= submit_tag %>
<% end %>

app/views/conversations/show.html.erb
<% provide(:title, "#{@conversation.subject}") %>

<h1><%= @conversation.subject %></h1>
<div class="row">
  <div class="col-md-5 col-md">
    <%= form_tag conversation_messages_path(@conversation), method: :post do %>
      <div>
        <%= text_area_tag :body %>
      </div>
      <%= submit_tag %>
    <% end %>
  </div>
  <div class="col-md-7 col-md">
    <% @conversation.receipts_for(current_user).each do |receipt| %>
      <div>
        <p class="lead"><%= receipt.message.sender.username %>:</p>
        <p class='well'><%= receipt.message.body %></p>
      </div>
    <% end %>
  </div>
</div>