config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  root "links#index"
  get '/about',         to: "static_pages#about", as:   "about"   #about_path/url
  get "/ask",           to: "questions#index",    as:   "ask"     #ask_path/url
  get "/new",           to: "links#index",        as:   "new"     #new_path/url
  get "/comments",      to: "comments#index",     as:   "comments"#comments_path/url
  delete "/signout",    to: "sessions#destroy",   as:   "signout" #signout_path/url
  get "/signin",        to: "sessions#new",       as:   "signin"  #signin_path/url
  post "/signin",       to: "sessions#create"
  get "/signup",        to: "users#new",          as:   "signup"  #signup_path/url

  resources :users
  resources :links do
    resources :comments, module: :links
  end
  resources :questions do
    resources :comments, module: :questions
  end
  resources :upvotes
  resources :conversations do
    resources :messages

    collection do
      get :inbox
      get :all, action: :index
      get :sent
      get :trash
    end
  end
  # redirect back to root_path if bad GET request is made
  get '*a' => redirect { |p, req| req.flash[:danger] = "Ah snap! Hitmunk couldn't find that page."; '/' }
end

app/models/link.rb
class Link < ApplicationRecord
  # Active Record Callbacks
  before_save { self.url = self.url.downcase }
  before_save :update_slug

  # Active Record Associations
  belongs_to :user
  has_many :upvotes, dependent: :destroy
  has_many :users_who_upvoted, through: :upvotes, source: :user
  has_many :comments, as: :commentable

  # Active Record Validations
  validates :title, presence: true, uniqueness: { case_sensitive: false }
  validates :url, presence: true, url: true, uniqueness: { case_sensitive: false }

  # refactor this into a scope later
  def self.order_by_popularity
    self.order('upvotes_count + comments_count desc')
  end

  # instance methods
  def already_liked_by?(user)
    users_who_upvoted.include? user
  end

  def update_slug
    self.slug = title.parameterize
  end

  def to_param
    slug
  end
end

app/controllers/links/comments_controller.rb
class Links::CommentsController < CommentsController
  before_action :set_commentable

  def index
    redirect_to root_path
  end

  private

  def set_commentable
    @commentable = Link.find_by_slug(params[:link_id])
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :require_signin, only: [:new, :create]
  # responds to GET /links
  def index
    @links = Link.order_by_popularity

    @links.each do |link|
      if current_user
        @current_vote = current_user.upvotes.find_by(link_id: link.id)
      end
    end
  end

  # responds to GET /links/new
  def new
    @link = current_user.links.new
  end

  # responds to POST /links/new
  def create
    @link = current_user.links.new(links_params)
    if @link.save # automatically calls @link.valid?
      calculate_points_for(current_user, 3)
      flash[:success] = "Boom! Your link has been successfully added."
      redirect_to links_url
    else
      render 'new' # automatically saves valid information on form
    end
  end

  # responds to GET /links/:id
  def show
    @link = Link.find_by_slug(params[:id])
  end

  def archive
    @link = Link.find_by_slug(params[:id])
    @link.archive
    flash[:success] = "#{@link.title} has been successfully archived!"
    redirect_to root_path
  end

  def unarchive
    @link = Link.find_by_slug(params[:id])
    @link.unarchive
    flash[:success] = "#{@link.title} has been successfully unarchived!"
    redirect_to root_path
  end

  private

  def links_params
    params.require(:link).permit(:title, :url)
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/index.html.erb
<% provide(:title, "Front Page") %>
<div class="row">
  <div class="col-md-12 col-md">
    <% @links.each do |link| %>
      <% unless link.archived? %>
        <li>
          <% unless link.already_liked_by?(current_user) %>
            <%= link_to upvotes_path(link), method: :post do %>
              <span class="glyphicon glyphicon-arrow-up"></span>
            <% end %>
          <% end %> |
          <%= link_to link_path(link) do %>
            <span class="glyphicon glyphicon-comment">
            </span>
            <%= pluralize(link.comments.size, "comment") %>
          <% end %>
            <strong><%= link_to "#{link.title}", link.url, target: :_blank %></strong>
          <em>
            (<%= time_ago_in_words(link.created_at) %> ago)
          </em> - <%= pluralize(link.upvotes.count, "upvote") %>
          by <%= link_to "#{link.user.username}", user_path(link.user) %>
          <% if logged_in? && current_user.admin? %>
            <strong><%= link_to "archive", "#" %></strong>
          <% end %>
        </li>
      <% end %>
    <% end %>
  </div>
  <div class="col-md-4 col-md">
  </div>
</div>

app/views/links/new.html.erb
<% provide(:title, "Add news link") %>
<div class="row">
  <div class="col-md-4 col-md">
    <h1>Add news link</h1>
    <%= form_for(@link, url: links_path(@link)) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> <!--f.object is @link -->

      <%= f.label :title %>
      <%= f.text_field :title, required: true, class: 'form-control', placeholder: "copy and paste title here" %>

      <%= f.label :url, "URL" %>
      <%= f.text_field :url, required: true, class: 'form-control', placeholder: "copy and paste link url here" %>

      <!-- @user.new.new_record? == true will issue a POST request -->
      <%= f.submit "Post link", class: "btn btn-primary",
                               method: :post %>
    <% end %>
  </div>
</div>

app/views/links/show.html.erb
<% provide(:title, "#{@link.title}") %>
<div class="row">
  <div class="col-md-5 col-md">
    <h2><%= link_to @link.title, @link.url, target: :_blank %></h2>
    <%= render partial: "comments/form", locals: { commentable: @link } %>
  </div>
  <div class="col-md-7 col-md">
    <h2>Comment Thread:</h2>
    <%= render partial: "comments/comments", locals: { commentable: @link } %>
  </div>
</div>