config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  root "links#index"
  get '/about',         to: "static_pages#about", as:   "about"   #about_path/url
  get "/ask",           to: "questions#index",    as:   "ask"     #ask_path/url
  get "/new",           to: "links#index",        as:   "new"     #new_path/url
  get "/comments",      to: "comments#index",     as:   "comments"#comments_path/url
  delete "/signout",    to: "sessions#destroy",   as:   "signout" #signout_path/url
  get "/signin",        to: "sessions#new",       as:   "signin"  #signin_path/url
  post "/signin",       to: "sessions#create"
  get "/signup",        to: "users#new",          as:   "signup"  #signup_path/url

  resources :users
  resources :links do
    resources :comments, module: :links
  end
  resources :questions do
    resources :comments, module: :questions
  end
  resources :upvotes
  resources :conversations do
    resources :messages

    collection do
      get :inbox
      get :all, action: :index
      get :sent
      get :trash
    end
  end
  # redirect back to root_path if bad GET request is made
  get '*a' => redirect { |p, req| req.flash[:danger] = "Ah snap! Hitmunk couldn't find that page."; '/' }
end

app/views/layouts/_defaults.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<link href="https://fonts.googleapis.com/css?family=Domine" rel="stylesheet">

app/views/layouts/_navbar.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <%= link_to "#{$SITE_TITLE}", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "New", new_path %></li>
        <li><%= link_to "Comments", comments_path %></li>
        <li><%= link_to "Ask HM", ask_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Submit<b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "News", new_link_path %></li>
            <li><%= link_to "Question", new_question_path %></li>
          </ul>
        </li>
        <% if logged_in? %>
         <li class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             <%= current_user.username %> <em>(<%= pluralize(current_user.points, "point") %>)</em>
             <% if current_user.mailbox.inbox.unread(current_user).count >= 1 %>
               <span class="glyphicon glyphicon-envelope"></span>
             <% end %>
             <b class="caret"></b>
           </a>
           <ul class="dropdown-menu">
             <li><%= link_to "Profile", user_path(current_user) %></li>
             <li><%= link_to "Settings", edit_user_path(current_user) %></li>
             <li><%= link_to "My Mailbox (#{current_user.mailbox.inbox.unread(current_user).count})", conversations_path(current_user) %></li>
             <li class="divider"></li>
             <li>
               <%= link_to "Log out", signout_path, method: :delete %>
             </li>
           </ul>
         </li>
        <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/defaults' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'shared/flash_messages' %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>